# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker:19.03.12

# open docker daemon service, need --privileged premission
services:
- name: docker:19.03.12-dind
  # if you need use repository by http portcol, uncomment next line
  command: ["--insecure-registry=47.95.254.230:8080"]

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DEV_DEPLOY_ACCOUNT: "kubernet"

stages:
  - build
  - deploy

build_dev:
  stage: build
  only:
    - tags
  script:
    - docker login -u ${habor_user_lab} -p ${habor_password_lab} harbor.belstardoc.com
    - echo "$env_lab" > .env
    - docker pull harbor.belstardoc.com/zm/local-folder-watcher:latest || true
    - docker build --cache-from harbor.belstardoc.com/zm/local-folder-watcher:latest -t harbor.belstardoc.com/zm/local-folder-watcher:latest .
    - docker tag harbor.belstardoc.com/zm/local-folder-watcher:latest harbor.belstardoc.com/zm/local-folder-watcher:$CI_COMMIT_REF_NAME
    - docker push harbor.belstardoc.com/zm/local-folder-watcher:latest
    - docker push harbor.belstardoc.com/zm/local-folder-watcher:$CI_COMMIT_REF_NAME

push_ali:
  stage: deploy
  only:
    - tags
  tags:
    - KH-HK
  when: manual
  script:
    - docker login -u ${habor_user_lab} -p ${habor_password_lab} harbor.belstardoc.com
    - docker login -u ${habor_user_ali} -p ${habor_password_ali} 47.95.254.230:8080
    - docker pull harbor.belstardoc.com/zm/local-folder-watcher:latest
    - docker pull harbor.belstardoc.com/zm/local-folder-watcher:$CI_COMMIT_REF_NAME
    - docker tag harbor.belstardoc.com/zm/local-folder-watcher:latest 47.95.254.230:8080/zm/local-folder-watcher:latest
    - docker tag harbor.belstardoc.com/zm/local-folder-watcher:$CI_COMMIT_REF_NAME 47.95.254.230:8080/zm/local-folder-watcher:$CI_COMMIT_REF_NAME
    - docker push 47.95.254.230:8080/zm/local-folder-watcher:latest
    - docker push 47.95.254.230:8080/zm/local-folder-watcher:$CI_COMMIT_REF_NAME